export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const GET_ALL_FAVOURITE = "GET_ALL_FAVOURITE";
export const DELETE_FAVOURITE = "DELETE_FAVOURITE";
